
const SET_PROJECT_DATA = 'SET_PROJECT_DATA',
		PAGER_ADD_TO_HISTORY = 'PAGER_ADD_TO_HISTORY',
		PAGER_CURRENT_PAGE = 'PAGER_CURRENT_PAGE',
		PAGER_REMOVE_LATEST = 'PAGER_REMOVE_LATEST',
		FILTER_BY_STATUS = 'FILTER_BY_STATUS',
		FILTER_OPENER = 'FILTER_OPENER';

export  {
	SET_PROJECT_DATA,
	PAGER_ADD_TO_HISTORY,
	PAGER_CURRENT_PAGE,
	PAGER_REMOVE_LATEST,
	FILTER_BY_STATUS,
	FILTER_OPENER
}
